export enum ActionType {
  TOGGLE_THEME = 'TOGGLE_THEME',
  FETCH_QOD = 'FETCH_QOD',
  FETCH_All_QOD = 'FETCH_All_QOD',
  SET_QOD = 'SET_QOD',
  FETCH_USER_QUOTES = 'FETCH_USER_QUOTES',
  USER_QUOTES_LOADING_TOGGLE = 'USER_QUOTES_LOADING_TOGGLE'
}